apiVersion: v1
kind: Service
metadata:
  name: simple-java-service
spec:
  type: LoadBalancer   # exposes service externally
  selector:
    app: simple-java-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
